apiVersion: v1
data:
  default.conf: |-
    server {
        listen 80 default_server;
        server_name _;
        default_type text/plain;

        location / {
            return 200 'Old app on $hostname pod\n';
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-1-configmap
