apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_view
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_view_role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_edit
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_edit_role
  apiGroup: rbac.authorization.k8s.io
